### PR TITLE
Rename "RTT" to RoundTripTime

### PR DESCRIPTION
**Pull request by alvestrand**
Partial resolution of issue #74

### CODE REVIEW

**Comment by alvestrand** [comment]
@vr000m @jan-ivar @fippo is thiis an acceptable resolution of #74?
I put "partial" in the description here, but now I can't figure out what else is needed for #74.

**Comment by alvestrand** [comment]
Closes #74 

That should be the magic token :-)

**Comment by vr000m** [comment]
Although we still need to move the rtt from the outbound to inbound remote

**Comment by jan-ivar** [comment]
@vr000m Is there an issue for that?

**Comment by fippo** [comment]
its #78

**Pull request merged**
