### PR TITLE
Add packetsDuplicated

### LINKED ISSUE #254: add packetsDuplicated as a result of #253
to make sure that the negative losses are due to duplicate packets. 

Should duplicate packet counter increase when:

1. FEC is applied?
2. Retransmission?
3. it is an actual duplicate packet. because a router transmitted a packet twice.

### PR DESCRIPTION
**Pull request by alvestrand**
Fixes #254

### CODE REVIEW

**Comment by vr000m** [comment]
RFC3550 determines that there might be duplicates because the loss may be negative 
and RFC3611 do not really define a duplicate packet as receiving the same sequence number more than once in a reporting period.

May be should add the following to clarify what we mean by duplicates, i.e., exact duplicates because sequence numbers will wrap around for some sessions: 
> The counter increases each time a duplicate packet with the same sequence number and payload is received (even if the same packet is received multiple times).

**Comment by alvestrand** [comment]
Clarify that multiple copies of the same packet make the counter go up multiple times.
Clarify that duplicates have same sequence number & content

**Comment by vr000m** [comment]
I believe the current proposal clarifies that the packetsDiscarded do not count for duplicates.

**Comment by alvestrand** [comment]
(if the payload has changed, SRTP will object, and we'll get packetFailedDecryption instead)

**Comment by vr000m** [comment]
Then the clarification just needs to be for, counter increases even if multiple copies of the same packet is received.

**Pull request merged**
