### PR TITLE
Remove RTCNetworkType and networkType fields

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by youennf** [comment]
Fixes https://github.com/w3c/webrtc-stats/issues/374

**Comment by henbos** [comment]
I wonder if the right thing to do is to add this to the obsolete section (which is what we've done with everything else that we've removed) or if with this one we add it to https://github.com/w3c/webrtc-provisional-stats ?

**Comment by alvestrand** [comment]
@youenn can you make a PR to add it to the provisional stats?
then we can merge this as soon as it's been added to provisional.

**Comment by henbos** [comment]
With the submission of https://github.com/w3c/webrtc-provisional-stats/pull/18, I'm happy to merge this PR

**Comment by youennf** [comment]
Let's merge it then!

**Pull request merged**
