### PR TITLE
adding total consent interval

### LINKED ISSUE #63: Missing consent interval in RTCIceCandidatePairStats
Currently, the consent interval is different for each browser, it would be nice to have a way to know what value is used by the browser.

@aboba @taylor-b comments? 

TPAC16 decision:
Go ahead and create PR.

### PR DESCRIPTION
**Pull request by vr000m**
fixes #63.

### CODE REVIEW

**Comment by henbos** [comment]
If lastResponseTimestamp of #213 is not enough of a heartbeat metric.

**Comment by taylor-b** [comment]
If we're adding `lastRequestTimestamp`, it would be more consistent to add `firstRequestTimestamp` rather than `sumCheckInterval`. Because `lastRequestTimestamp - firstRequestTimestamp` would be equivalent to `sumCheckInterval`.

**Comment by vr000m** [comment]
@taylor-b I am fine with your change, is the firstRequestTimestamp, the timestamp of the first connectivity check?

@henbos could you do taylor's change as part of your PR #213, so that I can just close this one?

**Comment by henbos** [comment]
SGTM

**Pull request closed without merging**
