### PR TITLE
s/remoteId/associateStatsId per discussion in #17

### PR DESCRIPTION
**Pull request by fippo**
@alvestrand @vr000m

(still need to figure out how to keep the ipr bot happy)

### CODE REVIEW

**Comment by alvestrand** [comment]
making any headway on getting some kind of w3c membership?
Or do we need to do the invited-expert thing?

**Comment by fippo** [comment]
that should be resolved now thanks to Frode!

**Comment by dontcallmedom** [comment]
I've nudged the IPR bot which is now happy.

**Comment by vr000m** [comment]
Fixes #17

**Pull request merged**
