### PR TITLE
Move {fir|pli|nack|sli}Count and qpSum out of baseclass to {in|out}bound (Editorial)

### PR DESCRIPTION
**Pull request by jan-ivar**
Fix for https://github.com/w3c/webrtc-stats/issues/312.

### CODE REVIEW

**Comment by jan-ivar** [comment]
[Preview](https://rawgit.com/w3c/webrtc-stats/4809e859b8f23b180f39aa13a433eb8c7ccb6a11/webrtc-stats.html#inboundrtpstats-dict*)

**Comment by alvestrand** [comment]
This means duplication of the stats into two dictionaries. Can we avoid the duplication of the descriptions? (ie replace one set with "see <other> for definition")?

**Comment by alvestrand** [comment]
QP is the one that has a long description that might get out of sync. The other ones are short.

**Comment by alvestrand** [comment]
Jan-Ivar will merge when the definition of qp is deduplicated.

**Comment by alvestrand** [comment]
@vr000m would like to review this prior to merge - discussing whether they should be nacksReceived and nacksSent rather than nackCount.

**Comment by vr000m** [comment]
When it was in the base class, the ambigious *Count name made sense because the text described how the counters were updated at the sender and receiver. Now that these metrics are being moved to the appropriate dictionary, we can add the suffix -Sent/-Received qualifier. 

If we are going down this path, I would encourage the -suffix, but that would require retiring the -Count metrics.

Browsers that have implemented these -Count metrics should also chime in? @henbos @aboba @jan-ivar @youennf

**Comment by na-g** [comment]
@vr000m, Firefox implements most of those counts, and I don't foresee being able to remove support for the *Count names any time soon. If the goal in renaming them is to remain consistent with other packet counters, should they be *PacketsSent/*PacketsReceived instead?

**Comment by jan-ivar** [comment]
@vr000m This PR is mostly editorial, shuffling around dictionaries in a manner hardly observable by JS. It is 99.9% web compatible (only minor reordering of members by name).

It therefore does not represent a renaming opportunity the way it might in other languages.

Renaming members would have significant web compat impact and should be considered independent of this editorial PR IMHO.

**Comment by na-g** [comment]
@jan-ivar and @vr000m, is there anything holding this PR request back that shouldn't be addressed in another issue?

**Comment by jan-ivar** [comment]
@vr000m @alvestrand In the interest of merging this, I've opened a separate issue https://github.com/w3c/webrtc-stats/issues/390 on `nacksReceived` and `nacksSent`.

OK to merge?

**Pull request merged**
