### PR TITLE
ice-server instead of stunserverconnection

### LINKED ISSUE #444: Type stunserverconnection should be stun-server-connection
For consistency with other types (e.g. local-candidate, not localcandidate).

### PR DESCRIPTION
**Pull request by lennart-csio**
Fixes #444

### CODE REVIEW

**Comment by vr000m** [comment]
Obsolete section should say thing got renamed.

**Comment by henbos** [comment]
TODO @vr000m Say what how you want the PR to be updated to reflect the old name in the obsolete section

**Comment by vr000m** [comment]
Looking at our previous decisions, we changed to `inbound-rtp` from `inboundrtp` without a an obsolete section.

**Comment by fippo** [comment]
And nobody ever implemented stunserverconnection either so no backward-compability issues

**Pull request merged**
